--CREATE USER SPACEFIT IDENTIFIED BY SPACEFIT;
--GRANT CONNECT, RESOURCE, CREATE VIEW TO SPACEFIT;

DROP TABLE "TB_MEMBER" CASCADE CONSTRAINTS;

CREATE TABLE "TB_MEMBER" (
	"MEM_NO"	NUMBER		NOT NULL,
	"GR_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"MEM_ID"	VARCHAR2(60)		NOT NULL    UNIQUE,
	"MEM_PWD"	VARCHAR2(60)		NOT NULL,
	"MEM_NAME"	VARCHAR2(30)		NOT NULL,
	"MEM_IDNO"	VARCHAR2(7)		NOT NULL,
	"MEM_PHONE"	VARCHAR2(11)		NOT NULL    UNIQUE,
	"MEM_MAIL"	VARCHAR2(60)		NULL    UNIQUE,
	"MEM_PROFILE"	VARCHAR2(120)		NULL,
	"MEM_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MEM_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MEM_STATUS"	CHAR(1)	DEFAULT 'Y'	CHECK (MEM_STATUS IN('Y', 'N', 'A', 'B')) 	NOT NULL
);

DROP SEQUENCE SEQ_MEMNO;
CREATE SEQUENCE SEQ_MEMNO NOCACHE;

COMMENT ON COLUMN "TB_MEMBER"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_MEMBER"."GR_NO" IS '회원등급 3개';

COMMENT ON COLUMN "TB_MEMBER"."MEM_ID" IS '아이디';

COMMENT ON COLUMN "TB_MEMBER"."MEM_PWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MEMBER"."MEM_IDNO" IS '주민번호';

COMMENT ON COLUMN "TB_MEMBER"."MEM_PHONE" IS '전화번호';

COMMENT ON COLUMN "TB_MEMBER"."MEM_MAIL" IS '이메일';

COMMENT ON COLUMN "TB_MEMBER"."MEM_PROFILE" IS 'resources/xxxxx/xxxx.jpg';

COMMENT ON COLUMN "TB_MEMBER"."MEM_ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "TB_MEMBER"."MEM_MODIFY_DATE" IS '정보수정일';

COMMENT ON COLUMN "TB_MEMBER"."MEM_STATUS" IS 'Y |  N  | A  |  B';



DROP TABLE "TB_REVIEW" CASCADE CONSTRAINTS;

CREATE TABLE "TB_REVIEW" (
	"RV_NO"	NUMBER		NOT NULL,
	"BOOK_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"RV_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"RV_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"RV_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"RV_STAR"	NUMBER		NOT NULL,
	"RV_STATUS"	CHAR(1) DEFAULT 'Y' CHECK (RV_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN "TB_REVIEW"."RV_NO" IS '후기번호';

COMMENT ON COLUMN "TB_REVIEW"."BOOK_NO" IS '예약번호';

COMMENT ON COLUMN "TB_REVIEW"."SPACE_NO" IS '공간번호';

COMMENT ON COLUMN "TB_REVIEW"."MEM_NO" IS '작성자회원번호';

COMMENT ON COLUMN "TB_REVIEW"."RV_CONTENT" IS '후기내용';

COMMENT ON COLUMN "TB_REVIEW"."RV_ENROLL_DATE" IS '후기작성일';

COMMENT ON COLUMN "TB_REVIEW"."RV_MODIFY_DATE" IS '후기수정일';

COMMENT ON COLUMN "TB_REVIEW"."RV_STAR" IS '평점';

COMMENT ON COLUMN "TB_REVIEW"."RV_STATUS" IS '후기상태';

DROP SEQUENCE SEQ_RVNO;
CREATE SEQUENCE SEQ_RVNO NOCACHE;



DROP TABLE TB_SPACE CASCADE CONSTRAINTS;

CREATE TABLE TB_SPACE (
	SPACE_NO	NUMBER		NOT NULL,
	SPACE_NAME	VARCHAR2(30)		NOT NULL    UNIQUE,
	SPACE_LIMIT	NUMBER		NOT NULL,
	SPACE_INFO	VARCHAR2(4000)		NOT NULL,
	SPACE_CATEGORY	VARCHAR2(300)		NOT NULL,
	SPACE_PIC	VARCHAR2(500)		NOT NULL,
	SPACE_EN_DATE	DATE	DEFAULT SYSDATE 
);

DROP SEQUENCE SEQ_SPNO;
CREATE SEQUENCE SEQ_SPNO NOCACHE;

COMMENT ON COLUMN "TB_SPACE"."SPACE_NO" IS '공간번호';

COMMENT ON COLUMN "TB_SPACE"."SPACE_NAME" IS '공간명';

COMMENT ON COLUMN "TB_SPACE"."SPACE_LIMIT" IS '수용인원';

COMMENT ON COLUMN "TB_SPACE"."SPACE_INFO" IS '공간설명';

COMMENT ON COLUMN "TB_SPACE"."SPACE_CATEGORY" IS '공간분류';

COMMENT ON COLUMN "TB_SPACE"."SPACE_PIC" IS '대표이미지경로';

COMMENT ON COLUMN "TB_SPACE"."SPACE_EN_DATE" IS '공간등록일';



DROP TABLE "TB_CART" CASCADE CONSTRAINTS;

CREATE TABLE "TB_CART" (
	"MEM_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"CART_LIMIT"	NUMBER		NOT NULL,
	"CART_DATE"	VARCHAR2(30)		NOT NULL,
	"CART_IN"	VARCHAR2(20)		NOT NULL,
	"CART_OUT"	VARCHAR2(20)		NOT NULL,
	"CART_PARKING"	CHAR(1) DEFAULT 'N' CHECK(CART_PARKING IN ('N','Y')),
	"CART_ANIMAL"	CHAR(1)	DEFAULT 'N'	CHECK(CART_ANIMAL IN ('N','Y')),
	"CART_STAND"	CHAR(1)	DEFAULT 'N'	CHECK(CART_STAND IN ('N','Y')),
	"CART_CHAIR"	CHAR(1)	DEFAULT 'N'	CHECK(CART_CHAIR IN ('N','Y')),
	"CART_PRICE"	NUMBER	DEFAULT 0	
);

COMMENT ON COLUMN "TB_CART"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_CART"."SPACE_NO" IS '공간번호';

COMMENT ON COLUMN "TB_CART"."CART_LIMIT" IS '요청인원';

COMMENT ON COLUMN "TB_CART"."CART_DATE" IS '대여예정일';

COMMENT ON COLUMN "TB_CART"."CART_IN" IS '체크인시간';

COMMENT ON COLUMN "TB_CART"."CART_OUT" IS '체크아웃시간';

COMMENT ON COLUMN "TB_CART"."CART_PARKING" IS '주차';

COMMENT ON COLUMN "TB_CART"."CART_ANIMAL" IS '반려동물';

COMMENT ON COLUMN "TB_CART"."CART_STAND" IS '보면대';

COMMENT ON COLUMN "TB_CART"."CART_CHAIR" IS '미니의자';

COMMENT ON COLUMN "TB_CART"."CART_PRICE" IS '가격';



DROP TABLE TB_LOVE CASCADE CONSTRAINTS;

CREATE TABLE TB_LOVE (
	SPACE_NO	NUMBER		NOT NULL,
	MEM_NO	NUMBER		NOT NULL,
	LOVE_DATE	DATE	DEFAULT SYSDATE
);

COMMENT ON COLUMN "TB_LOVE"."SPACE_NO" IS '공간번호';

COMMENT ON COLUMN "TB_LOVE"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_LOVE"."LOVE_DATE" IS '찜한날짜';



DROP TABLE "TB_BOOK" CASCADE CONSTRAINTS;

CREATE TABLE "TB_BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"PL_ID"	VARCHAR2(100)		NOT NULL,
	"BOOK_COUNT"	NUMBER		NOT NULL,
	"BOOK_DATE"	VARCHAR2(30)		NOT NULL,
	"BOOK_IN"	VARCHAR2(20)		NOT NULL,
	"BOOK_OUT"	VARCHAR2(20)		NOT NULL,
	"BOOK_PRICE"	NUMBER		NOT NULL,
	"BOOK_NAME"	VARCHAR2(20)		NOT NULL,
	"BOOK_PHONE"	VARCHAR2(13)		NOT NULL,
	"BOOK_EMAIL"	VARCHAR2(30)		NOT NULL,
	"BOOK_PURPOSE"	VARCHAR2(60)		NULL,
	"BOOK_ADD_CONTENT"	VARCHAR2(1500),
	"BOOK_CAR"	CHAR(1)	DEFAULT 'N'	 CHECK (BOOK_CAR IN('Y', 'N')),
	"BOOK_ANIMAL"	CHAR(1)	DEFAULT 'N'	CHECK (BOOK_ANIMAL IN('Y', 'N')),
	"BOOK_CHAIR"	CHAR(1)	DEFAULT 'N'	CHECK (BOOK_CHAIR IN('Y', 'N')),
	"BOOK_STAND"	CHAR(1)	DEFAULT 'N'	CHECK (BOOK_STAND IN('Y', 'N')),
	"BOOK_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOOK_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"BOOK_STATUS"	CHAR(1)	DEFAULT 'Y'	CHECK (BOOK_STATUS IN('Y', 'N')),
	"BOOK_CATEGORY"	VARCHAR2(20)	DEFAULT '예약확정'	NULL,
	"BOOK_CANCEL_REASON"	VARCHAR2(40)		NULL,
	"BOOK_CANCEL_CONTENT"	VARCHAR2(1500)		NULL
);

COMMENT ON COLUMN "TB_BOOK"."BOOK_NO" IS '예약번호';

COMMENT ON COLUMN "TB_BOOK"."SPACE_NO" IS '공간번호';

COMMENT ON COLUMN "TB_BOOK"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_BOOK"."PL_ID" IS '결제식별자';

COMMENT ON COLUMN "TB_BOOK"."BOOK_COUNT" IS '예약인원';

COMMENT ON COLUMN "TB_BOOK"."BOOK_DATE" IS '대여날짜 xxxx.xx.xx';

COMMENT ON COLUMN "TB_BOOK"."BOOK_IN" IS '체크인날짜 (숫자만)';

COMMENT ON COLUMN "TB_BOOK"."BOOK_OUT" IS '체크아웃날짜';

COMMENT ON COLUMN "TB_BOOK"."BOOK_PRICE" IS '가격';

COMMENT ON COLUMN "TB_BOOK"."BOOK_NAME" IS '예약자명';

COMMENT ON COLUMN "TB_BOOK"."BOOK_PHONE" IS '예약자연락처';

COMMENT ON COLUMN "TB_BOOK"."BOOK_EMAIL" IS '예약자이메일';

COMMENT ON COLUMN "TB_BOOK"."BOOK_PURPOSE" IS '사용목적';

COMMENT ON COLUMN "TB_BOOK"."BOOK_ADD_CONTENT" IS '요청사항';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CAR" IS '주차옵션';

COMMENT ON COLUMN "TB_BOOK"."BOOK_ANIMAL" IS '반려동물옵션';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CHAIR" IS '미니의자옵션';

COMMENT ON COLUMN "TB_BOOK"."BOOK_STAND" IS '보면대옵션';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CREATE_DATE" IS '신청일';

COMMENT ON COLUMN "TB_BOOK"."BOOK_MODIFY_DATE" IS '수정일';

COMMENT ON COLUMN "TB_BOOK"."BOOK_STATUS" IS '상태값(Y/N)';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CATEGORY" IS '예약현황';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CANCEL_REASON" IS '취소사유';

COMMENT ON COLUMN "TB_BOOK"."BOOK_CANCEL_CONTENT" IS '취소상세사유';

DROP SEQUENCE SEQ_BONO;
CREATE SEQUENCE SEQ_BONO NOCACHE;



DROP TABLE "TB_FILE" CASCADE CONSTRAINTS;

CREATE TABLE "TB_FILE" (
	"FILE_NO"	NUMBER		NOT NULL,
	"REF_BNO"	NUMBER		NOT NULL,
	"FILE_CATEGORY"	NUMBER		NOT NULL,
	"FILE_ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NULL,
	"FILE_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FILE_LEVEL"	NUMBER		NULL,
	"FILE_STATUS"	CHAR(1)	DEFAULT 'Y'	 CHECK (FILE_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN "TB_FILE"."FILE_NO" IS '파일번호';

COMMENT ON COLUMN "TB_FILE"."REF_BNO" IS '참조게시글번호';

COMMENT ON COLUMN "TB_FILE"."FILE_CATEGORY" IS '참조게시글카테고리(1공간/2:후기/3.홈페이지관리)';

COMMENT ON COLUMN "TB_FILE"."FILE_ORIGIN_NAME" IS '파일원본명';

COMMENT ON COLUMN "TB_FILE"."FILE_CHANGE_NAME" IS '파일수정명';

COMMENT ON COLUMN "TB_FILE"."FILE_PATH" IS '저장폴더경로';

COMMENT ON COLUMN "TB_FILE"."FILE_UPLOAD_DATE" IS '업로드일';

COMMENT ON COLUMN "TB_FILE"."FILE_LEVEL" IS '파일레벨';

COMMENT ON COLUMN "TB_FILE"."FILE_STATUS" IS '상태';

DROP SEQUENCE SEQ_FINO;
CREATE SEQUENCE SEQ_FINO NOCACHE;



DROP TABLE "TB_PAYLIST" CASCADE CONSTRAINTS;
CREATE TABLE "TB_PAYLIST" (
	"PL_ID"	    VARCHAR2(100) NOT NULL,
	"PL_STATUS"	VARCHAR2(1024) NOT NULL,
	"PL_TID"	VARCHAR2(1024) NOT NULL,
	"PL_MEM_NO"	NUMBER	NOT NULL,
	"PL_TYPE"	VARCHAR2(1024) NOT NULL,
	"PL_MCP_NO"	NUMBER NOT NULL,
	"PL_AMOUNT"	VARCHAR2(1024) NOT NULL,
	"PL_DISCOUNT_AMOUNT" VARCHAR2(1024),
	"PL_CARD_INFO"    VARCHAR2(1024),
	"PL_REQUEST_TIME"    DATE DEFAULT SYSDATE NOT NULL,
	"PL_APPROVED_TIME"   DATE NOT NULL ,
	"PL_PAYLOAD"	     VARCHAR2(1024)
);

COMMENT ON COLUMN "TB_PAYLIST"."PL_ID" IS '결제식별자';

COMMENT ON COLUMN "TB_PAYLIST"."PL_STATUS" IS '상태';

COMMENT ON COLUMN "TB_PAYLIST"."PL_TID" IS '결제고유번호';

COMMENT ON COLUMN "TB_PAYLIST"."PL_MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_PAYLIST"."PL_TYPE" IS '결제방법';

COMMENT ON COLUMN "TB_PAYLIST"."PL_MCP_NO" IS '발급된쿠폰번호';

COMMENT ON COLUMN "TB_PAYLIST"."PL_AMOUNT" IS '쿠폰 적용 전 금액';

COMMENT ON COLUMN "TB_PAYLIST"."PL_DISCOUNT_AMOUNT" IS '쿠폰 적용 후 금액';

COMMENT ON COLUMN "TB_PAYLIST"."PL_CARD_INFO" IS '결제 카드 정보';

COMMENT ON COLUMN "TB_PAYLIST"."PL_REQUEST_TIME" IS '결제 준비 요청 시각';

COMMENT ON COLUMN "TB_PAYLIST"."PL_APPROVED_TIME" IS '결제 승인 시각';

COMMENT ON COLUMN "TB_PAYLIST"."PL_PAYLOAD" IS '커스텀 정보';


DROP SEQUENCE SEQ_PLNO;
CREATE SEQUENCE SEQ_PLNO NOCACHE;



DROP TABLE "TB_COUPON" CASCADE CONSTRAINTS;

CREATE TABLE "TB_COUPON" (
	"CP_NO"	NUMBER		NOT NULL,
	"CP_NAME"	VARCHAR2(30)		NOT NULL,
	"CP_DISCOUNT"	NUMBER		NOT NULL,
	"CP_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CP_COUPON_TARGET"	VARCHAR2(1)	CHECK(CP_COUPON_TARGET IN('A', 'G', 'S'))	NOT NULL
);

COMMENT ON COLUMN "TB_COUPON"."CP_NO" IS '쿠폰번호';

COMMENT ON COLUMN "TB_COUPON"."CP_NAME" IS '쿠폰명';

COMMENT ON COLUMN "TB_COUPON"."CP_DISCOUNT" IS '할인금액';

COMMENT ON COLUMN "TB_COUPON"."CP_ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "TB_COUPON"."CP_COUPON_TARGET" IS '적용대상(전체A/그룹G/개별S)';

DROP SEQUENCE SEQ_CPNO;
CREATE SEQUENCE SEQ_CPNO
START WITH 10000
NOCYCLE
NOCACHE;



DROP TABLE "TB_BANNER" CASCADE CONSTRAINTS;

CREATE TABLE "TB_BANNER" (
	"BAN_NO"	NUMBER		NOT NULL,
	"BAN_NAME"	VARCHAR2(30)		NOT NULL,
	"BAN_STATUS"	VARCHAR2(1)	DEFAULT 'N'	CHECK(BAN_STATUS IN('Y', 'N')) NULL,
	"BAN_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"BAN_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"BAN_URL"	VARCHAR2(30)		NULL,
	"BAN_IMG"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "TB_BANNER"."BAN_NO" IS '배너번호';

COMMENT ON COLUMN "TB_BANNER"."BAN_NAME" IS '배너명';

COMMENT ON COLUMN "TB_BANNER"."BAN_STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "TB_BANNER"."BAN_ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "TB_BANNER"."BAN_MODIFY_DATE" IS '수정일';

COMMENT ON COLUMN "TB_BANNER"."BAN_URL" IS 'URL';

COMMENT ON COLUMN "TB_BANNER"."BAN_IMG" IS '배너이미지경로';

DROP SEQUENCE SEQ_BANNO;
CREATE SEQUENCE SEQ_BANNO NOCACHE;



DROP TABLE "TB_TERMS" CASCADE CONSTRAINTS;

CREATE TABLE "TB_TERMS" (
	"TERMS_NO"	NUMBER		NOT NULL,
	"TERMS_TITLE"	VARCHAR2(100)		NOT NULL,
	"TERMS_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"TERMS_STATUS"	VARCHAR2(1)	DEFAULT 'N'	CHECK(TERMS_STATUS IN('Y', 'N')) NULL,
	"TERMS_PAGE"	VARCHAR2(50)		NOT NULL,
	"TERMS_NOTE"	VARCHAR2(200)		NULL,
	"TERMS_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"TERMS_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "TB_TERMS"."TERMS_NO" IS '약관번호';

COMMENT ON COLUMN "TB_TERMS"."TERMS_TITLE" IS '이용약관명';

COMMENT ON COLUMN "TB_TERMS"."TERMS_CONTENT" IS '약관내용';

COMMENT ON COLUMN "TB_TERMS"."TERMS_STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "TB_TERMS"."TERMS_PAGE" IS '게시영역';

COMMENT ON COLUMN "TB_TERMS"."TERMS_NOTE" IS '비고';

COMMENT ON COLUMN "TB_TERMS"."TERMS_ENROLL_DATE" IS '등록일';

COMMENT ON COLUMN "TB_TERMS"."TERMS_MODIFY_DATE" IS '수정일';

DROP SEQUENCE SEQ_TENO;
CREATE SEQUENCE SEQ_TENO NOCACHE;



DROP TABLE "TB_MCP" CASCADE CONSTRAINTS;

CREATE TABLE "TB_MCP" (
	"MCP_NO"NUMBER		NOT NULL,
	"CP_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"CP_STATUS"	CHAR(1)	DEFAULT 'Y'	CHECK(CP_STATUS IN('Y', 'N')) NULL,
	"CP_USE"	CHAR(1)	DEFAULT 'N'	CHECK(CP_USE IN('Y', 'N')) NULL,
	"CP_START_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CP_END_DATE"	DATE		NOT NULL
);
COMMENT ON COLUMN "TB_MCP"."MCP_NO" IS '발급된쿠폰번호';

COMMENT ON COLUMN "TB_MCP"."CP_NO" IS '쿠폰번호';

COMMENT ON COLUMN "TB_MCP"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_MCP"."CP_STATUS" IS '유효상태(Y/N)';

COMMENT ON COLUMN "TB_MCP"."CP_USE" IS '사용여부(Y/N)';

COMMENT ON COLUMN "TB_MCP"."CP_START_DATE" IS '발급일';

COMMENT ON COLUMN "TB_MCP"."CP_END_DATE" IS '만료일';

DROP SEQUENCE SEQ_MCNO;
CREATE SEQUENCE SEQ_MCNO NOCACHE;



DROP TABLE TB_QNA CASCADE CONSTRAINTS;
CREATE TABLE "TB_QNA" (
	"QNA_NO"	NUMBER		NOT NULL,
    "QNA_CATEGORY"	VARCHAR2(6)	NOT NULL CHECK(QNA_CATEGORY IN('공간', '결제', '예약', '기타')),
	"QNA_SPACE_NO"	NUMBER		NOT NULL,
	"QNA_TITLE"	VARCHAR2(100)		NOT NULL,
	"QNA_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"QNA_MEM_NO"	NUMBER		NOT NULL,
	"QNA_GROUP"	NUMBER	DEFAULT 0	NOT NULL,
	"QNA_REF_NO"	NUMBER,
	"QNA_CREATE_DATE"	DATE	DEFAULT SYSDATE,
	"QNA_UPDATE_DATE"	DATE	DEFAULT SYSDATE,
	"QNA_COUNT"	NUMBER	DEFAULT 0	NULL,
	"QNA_STATUS"	VARCHAR2(1) DEFAULT 'Y'	CHECK(QNA_STATUS IN('Y', 'N')),
	"QNA_PUBLIC"	VARCHAR2(1) DEFAULT 'Y' CHECK(QNA_PUBLIC IN('Y', 'N')),
	"QNA_PWD"	VARCHAR2(30)
);

COMMENT ON COLUMN "TB_QNA"."QNA_NO" IS '글번호';

COMMENT ON COLUMN "TB_QNA"."QNA_TITLE" IS '제목';

COMMENT ON COLUMN "TB_QNA"."QNA_CONTENT" IS '내용';

COMMENT ON COLUMN "TB_QNA"."QNA_MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_QNA"."QNA_GROUP" IS '글깊이';

COMMENT ON COLUMN "TB_QNA"."QNA_REF_NO" IS '참조글번호';

COMMENT ON COLUMN "TB_QNA"."QNA_CREATE_DATE" IS '작성날짜';

COMMENT ON COLUMN "TB_QNA"."QNA_UPDATE_DATE" IS '수정일';

COMMENT ON COLUMN "TB_QNA"."QNA_COUNT" IS '조회수';

COMMENT ON COLUMN "TB_QNA"."QNA_STATUS" IS '활성화여부';

COMMENT ON COLUMN "TB_QNA"."QNA_PUBLIC" IS '비밀글여부';

COMMENT ON COLUMN "TB_QNA"."QNA_PWD" IS '비밀번호';

COMMENT ON COLUMN "TB_QNA"."QNA_CATEGORY" IS '분류';

COMMENT ON COLUMN "TB_QNA"."QNA_SPACE_NO" IS '공간번호';

DROP SEQUENCE SEQ_QNNO;
CREATE SEQUENCE SEQ_QNNO NOCACHE;



DROP TABLE "TB_NOTICE" CASCADE CONSTRAINTS;
CREATE TABLE "TB_NOTICE" (
	"NT_NO"	NUMBER NOT NULL,
	"NT_TITLE" VARCHAR2(100) NOT NULL ,
	"NT_CONTENT" VARCHAR2(4000) NOT NULL ,
	"NT_MEM_NO" NUMBER NOT NULL ,
	"NT_COUNT" NUMBER DEFAULT 0,
	"NT_CREATE_DATE" DATE DEFAULT SYSDATE	,
	"NT_UPDATE_DATE" DATE DEFAULT SYSDATE	,
	"NT_STATUS"	VARCHAR2(1) DEFAULT 'Y' CHECK(NT_STATUS IN('Y', 'N')),
	"NT_CATEGORY" VARCHAR2(15) CHECK(NT_CATEGORY IN('이벤트', '일반')) NOT NULL
);

COMMENT ON COLUMN "TB_NOTICE"."NT_NO" IS '글번호';

COMMENT ON COLUMN "TB_NOTICE"."NT_TITLE" IS '제목';

COMMENT ON COLUMN "TB_NOTICE"."NT_CONTENT" IS '내용';

COMMENT ON COLUMN "TB_NOTICE"."NT_MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_NOTICE"."NT_COUNT" IS '조회수';

COMMENT ON COLUMN "TB_NOTICE"."NT_CREATE_DATE" IS '작성날짜';

COMMENT ON COLUMN "TB_NOTICE"."NT_UPDATE_DATE" IS '수정일';

COMMENT ON COLUMN "TB_NOTICE"."NT_STATUS" IS '활성화여부';

COMMENT ON COLUMN "TB_NOTICE"."NT_CATEGORY" IS '분류(이벤트|일반)';

DROP SEQUENCE SEQ_NONO;
CREATE SEQUENCE SEQ_NONO NOCACHE;


	
DROP TABLE "TB_FAQ" CASCADE CONSTRAINTS;
CREATE TABLE "TB_FAQ" (
	"FAQ_NO" NUMBER NOT NULL,
	"FAQ_TITLE" VARCHAR2(100) NOT NULL ,
	"FAQ_CONTENT" VARCHAR2(4000) NOT NULL ,
    	"FAQ_MEM_NO" NUMBER NOT NULL,
	"FAQ_CREATE_DATE" DATE DEFAULT SYSDATE,
	"FAQ_UPDATE_DATE" DATE DEFAULT SYSDATE,
	"FAQ_STATUS" VARCHAR2(1) DEFAULT 'Y' CHECK(FAQ_STATUS IN('Y', 'N'))	
);

COMMENT ON COLUMN "TB_FAQ"."FAQ_NO" IS '글번호';

COMMENT ON COLUMN "TB_FAQ"."FAQ_TITLE" IS '제목';

COMMENT ON COLUMN "TB_FAQ"."FAQ_CONTENT" IS '내용';

COMMENT ON COLUMN "TB_FAQ"."FAQ_MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_FAQ"."FAQ_CREATE_DATE" IS '작성일';

COMMENT ON COLUMN "TB_FAQ"."FAQ_UPDATE_DATE" IS '수정일';

COMMENT ON COLUMN "TB_FAQ"."FAQ_STATUS" IS '활성화여부';

DROP SEQUENCE SEQ_FANO;
CREATE SEQUENCE SEQ_FANO NOCACHE;



DROP TABLE "TB_GRADE" CASCADE CONSTRAINTS;

CREATE TABLE "TB_GRADE" (
	"GR_NO"	NUMBER		NOT NULL,
	"GR_NAME"	VARCHAR2(20)		NOT NULL,
	"GR_COND"	NUMBER		NOT NULL
);

DROP SEQUENCE SEQ_GRNO;

CREATE SEQUENCE SEQ_GRNO NOCACHE;



DROP TABLE "TB_REPORT" CASCADE CONSTRAINTS;

CREATE TABLE "TB_REPORT" (
	"RPT_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"RPT_MEM_NO"	NUMBER		NOT NULL,
	"RPT_REASON_NO"	NUMBER		NOT NULL,
	"RPT_REF_CAT"	NUMBER		NOT NULL      CHECK (RPT_REF_CAT IN ('1', '2')),
	"RPT_REF_NO"	NUMBER		NOT NULL,
	"RPT_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "TB_REPORT"."MEM_NO" IS '신고한회원번호';

COMMENT ON COLUMN "TB_REPORT"."RPT_MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_REPORT"."RPT_REASON_NO" IS '신고사유번호';

COMMENT ON COLUMN "TB_REPORT"."RPT_REF_CAT" IS '후기글 1 | 댓글 2';

DROP SEQUENCE SEQ_RPTNO;

CREATE SEQUENCE SEQ_RPTNO NOCACHE;



DROP TABLE "TB_RPT_RSN" CASCADE CONSTRAINTS;

CREATE TABLE "TB_RPT_RSN" (
	"RPT_REASON_NO"	NUMBER		NOT NULL,
	"RPT_REASON"	VARCHAR2(90)		NOT NULL
);

COMMENT ON COLUMN "TB_RPT_RSN"."RPT_REASON_NO" IS '신고사유번호';

COMMENT ON COLUMN "TB_RPT_RSN"."RPT_REASON" IS '신고사유';



DROP TABLE "TB_COMMENT" CASCADE CONSTRAINTS;

CREATE TABLE "TB_COMMENT" (
	"COM_NO"	NUMBER		NOT NULL,
	"RV_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(60)		NOT NULL,
	"COM_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"COM_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"COM_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"COM_PARENT_NO"	NUMBER	DEFAULT 0	NULL,
	"COM_STATUS"	CHAR(1)	DEFAULT 'Y'	CHECK(COM_STATUS IN('Y', 'N')) NULL
);

COMMENT ON COLUMN "TB_COMMENT"."COM_NO" IS '댓글번호';

COMMENT ON COLUMN "TB_COMMENT"."RV_NO" IS '후기번호';

COMMENT ON COLUMN "TB_COMMENT"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_COMMENT"."COM_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "TB_COMMENT"."COM_ENROLL_DATE" IS '댓글작성일';

COMMENT ON COLUMN "TB_COMMENT"."COM_MODIFY_DATE" IS '댓글수정일';

COMMENT ON COLUMN "TB_COMMENT"."COM_PARENT_NO" IS '이 댓글이 참조하는 댓글번호 (만일 원글일 경우 0)';

DROP SEQUENCE SEQ_COMNO;

CREATE SEQUENCE SEQ_COMNO NOCACHE;




DROP TABLE "TB_LIKE" CASCADE CONSTRAINTS;

CREATE TABLE "TB_LIKE" (
	"LIKE_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"LIKE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "TB_LIKE"."MEM_NO" IS '회원번호';

DROP SEQUENCE SEQ_LIKENO;
CREATE SEQUENCE SEQ_LIKENO NOCACHE;



ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"MEM_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "PK_TB_REVIEW" PRIMARY KEY (
	"RV_NO"
);

ALTER TABLE "TB_SPACE" ADD CONSTRAINT "PK_TB_SPACE" PRIMARY KEY (
	"SPACE_NO"
);

ALTER TABLE "TB_LOVE" ADD CONSTRAINT "PK_TB_LOVE" PRIMARY KEY (
	"SPACE_NO",
	"MEM_NO"
);

ALTER TABLE "TB_BOOK" ADD CONSTRAINT "PK_TB_BOOK" PRIMARY KEY (
	"BOOK_NO"
);

ALTER TABLE "TB_FILE" ADD CONSTRAINT "PK_TB_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "TB_PAYLIST" ADD CONSTRAINT "PK_TB_PAYLIST" PRIMARY KEY (
	"PL_ID"
);

ALTER TABLE "TB_COUPON" ADD CONSTRAINT "PK_TB_COUPON" PRIMARY KEY (
	"CP_NO"
);

ALTER TABLE "TB_BANNER" ADD CONSTRAINT "PK_TB_BANNER" PRIMARY KEY (
	"BAN_NO"
);

ALTER TABLE "TB_TERMS" ADD CONSTRAINT "PK_TB_TERMS" PRIMARY KEY (
	"TERMS_NO"
);

ALTER TABLE "TB_MCP" ADD CONSTRAINT "PK_TB_MCP" PRIMARY KEY (
	"MCP_NO"
);

ALTER TABLE "TB_QNA" ADD CONSTRAINT "PK_TB_QNA" PRIMARY KEY (
	"QNA_NO"
);

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "PK_TB_NOTICE" PRIMARY KEY (
	"NT_NO"
);

ALTER TABLE "TB_FAQ" ADD CONSTRAINT "PK_TB_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

ALTER TABLE "TB_GRADE" ADD CONSTRAINT "PK_TB_GRADE" PRIMARY KEY (
	"GR_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "PK_TB_REPORT" PRIMARY KEY (
	"RPT_NO"
);

ALTER TABLE "TB_RPT_RSN" ADD CONSTRAINT "PK_TB_RPT_RSN" PRIMARY KEY (
	"RPT_REASON_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "PK_TB_COMMENT" PRIMARY KEY (
	"COM_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "PK_TB_LIKE" PRIMARY KEY (
	"LIKE_NO"
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "FK_TB_GRADE_TO_TB_MEMBER_1" FOREIGN KEY (
	"GR_NO"
)
REFERENCES "TB_GRADE" (
	"GR_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_BOOK_TO_TB_REVIEW_1" FOREIGN KEY (
	"BOOK_NO"
)
REFERENCES "TB_BOOK" (
	"BOOK_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_REVIEW_1" FOREIGN KEY (
	"SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REVIEW_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_CART" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CART_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_CART" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_CART_1" FOREIGN KEY (
	"SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_LOVE" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_LOVE_1" FOREIGN KEY (
	"SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_LOVE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_LOVE_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_BOOK" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_BOOK_1" FOREIGN KEY (
	"SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_BOOK" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_BOOK_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_BOOK" ADD CONSTRAINT "FK_TB_PAYLIST_TO_TB_BOOK_1" FOREIGN KEY (
	"PL_ID"
)
REFERENCES "TB_PAYLIST" (
	"PL_ID"
);

ALTER TABLE "TB_PAYLIST" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_PAYLIST_1" FOREIGN KEY (
	"PL_MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_PAYLIST" ADD CONSTRAINT "FK_TB_MCP_TO_TB_PAYLIST_1" FOREIGN KEY (
	"PL_MCP_NO"
)
REFERENCES "TB_MCP" (
	"MCP_NO"
);

ALTER TABLE "TB_MCP" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_MCP_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_MCP" ADD CONSTRAINT "FK_TB_COUPON_TO_TB_MCP_1" FOREIGN KEY (
	"CP_NO"
)
REFERENCES "TB_COUPON" (
	"CP_NO"
);

ALTER TABLE "TB_QNA" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_QNA_1" FOREIGN KEY (
	"QNA_SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_QNA" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_QNA_1" FOREIGN KEY (
	"QNA_MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_QNA" ADD CONSTRAINT "FK_TB_QNA_TO_TB_QNA_1" FOREIGN KEY (
	"QNA_REF_NO"
)
REFERENCES "TB_QNA" (
	"QNA_NO"
);

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_NOTICE_1" FOREIGN KEY (
	"NT_MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_FAQ" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_FAQ_1" FOREIGN KEY (
	"FAQ_MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPORT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPORT_2" FOREIGN KEY (
	"RPT_MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_RPT_RSN_TO_TB_REPORT_1" FOREIGN KEY (
	"RPT_REASON_NO"
)
REFERENCES "TB_RPT_RSN" (
	"RPT_REASON_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_REVIEW_TO_TB_COMMENT_1" FOREIGN KEY (
	"RV_NO"
)
REFERENCES "TB_REVIEW" (
	"RV_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_COMMENT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_SPACE_TO_TB_LIKE_1" FOREIGN KEY (
	"SPACE_NO"
)
REFERENCES "TB_SPACE" (
	"SPACE_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_LIKE_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

-- COMMIT;



--------------------------------------------------------추가된 부분-----------------------------------------------------------

ALTER TABLE TB_MEMBER ADD MEM_ADM_FLAG CHAR(1) DEFAULT 'U' CHECK (MEM_ADM_FLAG IN ('A', 'U'));
ALTER TABLE TB_MEMBER MODIFY MEM_PWD VARCHAR2(1024);
ALTER TABLE TB_MEMBER MODIFY MEM_STATUS CHAR(1)	DEFAULT 'Y'	CHECK (MEM_STATUS IN('Y', 'N', 'B'));
COMMENT ON COLUMN "TB_MEMBER"."MEM_STATUS" IS 'Y |  N  |  B';
COMMENT ON COLUMN "TB_MEMBER"."MEM_ADM_FLAG" IS 'A  |  U';





ALTER TABLE TB_MCP RENAME COLUMN CP_STATUS TO MCP_STATUS;
ALTER TABLE TB_MCP RENAME COLUMN CP_USE TO MCP_USE;
ALTER TABLE TB_MCP RENAME COLUMN CP_START_DATE TO MCP_START_DATE;
ALTER TABLE TB_MCP RENAME COLUMN CP_END_DATE TO MCP_END_DATE;

ALTER TABLE TB_COUPON DROP COLUMN CP_COUPON_TARGET;




COMMENT ON COLUMN "TB_BOOK"."BOOK_IN" IS '체크인시간(숫자만)';
COMMENT ON COLUMN "TB_BOOK"."BOOK_OUT" IS '체크아웃시간';


ALTER TABLE TB_REVIEW MODIFY RV_CONTENT NULL;

COMMIT;